### ISSUE TITLE
does it support all printer network?

### ISSUE THREAD

**Issue by ul-rotha** [benoitverstraete/network_pos_printer#1]
does it support all printer network?

**Comment by benoitverstraete** [comment]
Hi @ul-rotha, 

It works only for printers that implement the POS script (usually thermal receipt printers).

**Comment by ul-rotha** [comment]
can i use with wifi?

**Comment by benoitverstraete** [comment]
Hi @ul-rotha,

Yes, the printer have to receive an IP address, whether it is by ethernet or wifi.
